set(_CATKIN_CURRENT_PACKAGE "vision")
set(vision_VERSION "0.0.0")
set(vision_MAINTAINER "Ishrat <badami@vision.rwth-aachen.de>, Lucas <beyer@vision.rwth-aachen.de>")
set(vision_PACKAGE_FORMAT "1")
set(vision_BUILD_DEPENDS "roscpp" "sensor_msgs" "opencv2" "cv_bridge")
set(vision_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "opencv2" "cv_bridge")
set(vision_BUILDTOOL_DEPENDS "catkin")
set(vision_BUILDTOOL_EXPORT_DEPENDS )
set(vision_EXEC_DEPENDS "roscpp" "sensor_msgs" "opencv2" "cv_bridge")
set(vision_RUN_DEPENDS "roscpp" "sensor_msgs" "opencv2" "cv_bridge")
set(vision_TEST_DEPENDS )
set(vision_DOC_DEPENDS )
set(vision_DEPRECATED "")